### PR TITLE
Targets mapped event before merging update #114

### PR DESCRIPTION
**Pull request by atomashpolskiy**
@andrus , @vitalz, check this out

### CODE REVIEW

**Comment by andrus** [comment]
Perhaps we can make ```TargetPropertyWriter.write(..)``` void as it won't be doing value comparison.

**Comment by atomashpolskiy** [comment]
@andrus , fixed

**Comment by atomashpolskiy** [comment]
@andrus , @vitalz, is this still needed?

**Comment by andrus** [comment]
I'd say let's apply it.

**Comment by atomashpolskiy** [comment]
rebased and merged to master

**Pull request closed without merging**
