### PR TITLE
Issue35

### PR DESCRIPTION
**Pull request by atomashpolskiy**
For some reason I did not pull-requested this earlier

### CODE REVIEW

**Comment by andrus** [comment]
@atomashpolskiy : Testing pull request, I am getting the following error in CreateOrUpdateIT.test_ExtraSrcColumns. This test was added recently per #59.

org.apache.cayenne.exp.ExpressionException: [v.4.0.M3.debfa94 May 22 2015 16:06:39] Can't resolve path component: [Etl1t.noSuchProperty].
	at org.apache.cayenne.map.PathComponentIterator.invalidPathException(PathComponentIterator.java:145)
	at org.apache.cayenne.map.PathComponentIterator.next(PathComponentIterator.java:133)
	at org.apache.cayenne.map.ObjEntity$DBPathConverter.toDbPath(ObjEntity.java:1141)
	at org.apache.cayenne.map.ObjEntity$DBPathConverter.transform(ObjEntity.java:1185)
	at org.apache.cayenne.exp.Expression.transformExpression(Expression.java:647)
	at org.apache.cayenne.exp.Expression.transform(Expression.java:598)
	at org.apache.cayenne.map.ObjEntity.translateToDbPath(ObjEntity.java:1077)
	at com.nhl.link.move.runtime.path.PathNormalizer$1.doNormalize(PathNormalizer.java:105)
	at com.nhl.link.move.runtime.path.PathNormalizer$1.getAttributeInfo(PathNormalizer.java:95)
	at com.nhl.link.move.runtime.path.PathNormalizer$1.normalizeValue(PathNormalizer.java:81)
	at com.nhl.link.move.runtime.task.createorupdate.RowConverter.convert(RowConverter.java:44)
	at com.nhl.link.move.runtime.task.createorupdate.RowConverter.convert(RowConverter.java:31)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.convertSrc(CreateOrUpdateSegmentProcessor.java:64)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.process(CreateOrUpdateSegmentProcessor.java:56)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateTask$1.process(CreateOrUpdateTask.java:74)
	at com.nhl.link.move.batch.BatchRunner.run(BatchRunner.java:54)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateTask.run(CreateOrUpdateTask.java:60)
	at com.nhl.link.move.runtime.task.BaseTask.run(BaseTask.java:29)
	at com.nhl.link.move.itest.CreateOrUpdateIT.test_ExtraSrcColumns(CreateOrUpdateIT.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by atomashpolskiy** [comment]
@andrus, this branch was created earlier, so you probably need to merge changes from issue #59 into anonymous EntityPathNormalizer#normalize in com.nhl.link.move.runtime.path.PathNormalizer#createNormalizer (there is a simple IF condition to check non-existant attributes).

**Comment by andrus** [comment]
I was merging to master that already includes #59.

**Comment by atomashpolskiy** [comment]
I suppose you merged com.nhl.link.move.runtime.path.PathNormalizer incorrectly, otherwise PathNormalizer$1.doNormalize would not be called. Please check again, I believe final version should be like in this request but with IF condition from #59.

**Comment by atomashpolskiy** [comment]
Rebased request against current master and created new branch in order to avoid merges: #66

**Pull request closed without merging**
